// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import "time"

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Age       int32     `gorm:"column:age;not null" json:"age"`
	UserName  string    `gorm:"column:user_name;not null" json:"user_name"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Phone     string    `gorm:"column:phone;not null" json:"phone"`
	RoleName  string    `gorm:"column:role_name;not null" json:"role_name"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
