system:
  mode: "dev"
  start_time: "2020-10-01"
  machine_id: 1

log:
  prefix: "[user-service]"
  level: "error"
  filename: "./logs/user-service.log"
  max_size: 200
  max_age: 30
  max_backups: 7

