apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans

system:
  mode: "release"  # test/debug/release
  start_time: "2021-7-15"
  machine_id: 1
  port: 8090

log:
  prefix: "[user-service]"
  level: "warn"
  file_name: "./logs/user-service.log"
  max_size: 200
  max_age: 30
  max_backups: 7