apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-ddd-action-redis
  namespace: dapr-ddd-action-redis
spec:
  type: bindings.redis
  version: v1
  metadata:
  - name: redisHost
    value: 127.0.0.1:6379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
