// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import "time"

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 用户表id
	Username   string    `gorm:"column:username;not null" json:"username"`          // 用户名
	Password   string    `gorm:"column:password;not null" json:"password"`          // 用户密码，MD5加密
	Email      string    `gorm:"column:email" json:"email"`
	Phone      string    `gorm:"column:phone" json:"phone"`
	Question   string    `gorm:"column:question" json:"question"`                // 找回密码问题
	Answer     string    `gorm:"column:answer" json:"answer"`                    // 找回密码答案
	Role       int32     `gorm:"column:role;not null" json:"role"`               // 角色0-管理员,1-普通用户
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null" json:"update_time"` // 最后一次更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
