apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ../kubernetes
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-service
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o ../kubernetes
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-service
    spec:
      containers:
        - image: go-kratos/beer-catalog-service:0.1.0
          name: catalog-service
          resources: {}
      hostname: catalog-service
      restartPolicy: Always
status: {}
